# Jekyll Specific Stuff
markdown: rdiscount
pygments: true
permalink: /posts/:title
paginate: 10 # the number of post per page
rdiscount:
  extensions: [smart]

# User Options
name: Sean Oliver
baseurl:   # Leave this blank unless you are using a directory other than the root directory (Do not use a trailing slash '/')
description: 'Stories about products and personal betterment.'
email: sean@seanoliver.me
twitter: seanoliver
icon_url: /images/profile.jpeg
disqus_shortname: seanoliver

# Color Options
text_color: '#444444'
accent_color: '#d95e3f'
hover_color: '#a7543f'
subtle_color: '#999999'
subtle_border: '#e9e9e9'
title_color: '#222222'
text_on_accent_color: '#ffffff'
header_background: '#385975'
header_text_color: '#dfe6ec'
header_accent_color: '#ffffff'
header_title_color: '#ffffff'
header_subtle_color: '#597790'
header_subtle_border: '#597790'
background: '#fcfcfc'
post_background:

# Footer
footer_title: 
footer_description: 
social_links_title: 
github_url: https://github.com/seanoliver
flickr_url: 
instagram_url: http://instagram.com/soliver87
vimeo_url: 
facebook_url: https://www.facebook.com/seane
google_plus_url: 
pinterest_url: 
tumblr_url: 
linkedin_url: www.linkedin.com/in/soliver87
dribbble_url: 
lastfm_url: 
rdio_url: 
spotify_url: 
skype_url: 
soundcloud_url: 
behance_url: 
